# Generated by Django 5.2.7 on 2025-11-29 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество еды')),
                ('service_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество обслуживания')),
                ('atmosphere', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Атмосфера')),
                ('cleanliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Чистота')),
                ('food_taste', models.CharField(choices=[('excellent', 'Очень вкусная'), ('good', 'Вкусная'), ('average', 'Нормальная'), ('poor', 'Не очень'), ('bad', 'Не вкусная')], max_length=20, verbose_name='Вкус еды')),
                ('portion_size', models.CharField(choices=[('large', 'Очень большие'), ('normal', 'Нормальные'), ('small', 'Маленькие')], max_length=20, verbose_name='Размер порций')),
                ('speed_service', models.CharField(choices=[('fast', 'Очень быстро'), ('normal', 'Нормально'), ('slow', 'Медленно'), ('very_slow', 'Очень медленно')], max_length=20, verbose_name='Скорость обслуживания')),
                ('staff_friendliness', models.CharField(choices=[('excellent', 'Очень вежливые'), ('good', 'Вежливые'), ('average', 'Нормальные'), ('poor', 'Не очень вежливые')], max_length=20, verbose_name='Вежливость персонала')),
                ('price_quality', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное'), ('poor', 'Плохое')], max_length=20, verbose_name='Соотношение цены и качества')),
                ('child_friendly', models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('average', 'Нормально'), ('poor', 'Плохо')], max_length=20, verbose_name='Удобство для детей')),
                ('recommend', models.CharField(choices=[('yes', 'Да, обязательно'), ('maybe', 'Возможно'), ('no', 'Нет')], max_length=10, verbose_name='Рекомендация')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('overall_rating', models.FloatField(verbose_name='Общая оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка кафе',
                'verbose_name_plural': 'Оценки кафе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
