# Generated by Django 5.2.7 on 2025-12-03 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_caferating_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время начала')),
                ('event_duration', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Продолжительность (часы)')),
                ('event_end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('guests_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество гостей')),
                ('event_type', models.CharField(choices=[('birthday', 'День рождения'), ('holiday', 'Праздник'), ('graduation', 'Выпускной'), ('other', 'Другое')], max_length=20, verbose_name='Тип мероприятия')),
                ('services', models.JSONField(default=list, help_text='Список выбранных услуг', verbose_name='Дополнительные услуги')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('comments', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('base_cost', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Базовая стоимость')),
                ('services_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость услуг')),
                ('total_cost', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование мероприятия',
                'verbose_name_plural': 'Бронирования мероприятий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_date', 'event_time'], name='homepage_bo_event_d_96d126_idx'), models.Index(fields=['status'], name='homepage_bo_status_787242_idx')],
            },
        ),
    ]
