# Generated by Django 5.2.7 on 2025-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('breakfast', 'Завтраки'), ('main', 'Основные блюда'), ('salad', 'Салаты'), ('drink', 'Напитки'), ('dessert', 'Десерты'), ('child', 'Детские блюда')], default='main', max_length=20, verbose_name='Категория')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на изображение')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав (через запятую)')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории')),
                ('protein', models.CharField(blank=True, max_length=50, verbose_name='Белки')),
                ('carbs', models.CharField(blank=True, max_length=50, verbose_name='Углеводы')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'title'],
            },
        ),
    ]
